### PR TITLE
feat: add nginx proxy

### LINKED ISSUE #904: docker: add proxy to only export one port

### PR DESCRIPTION
**Pull request by Meierschlumpf**
<br/>
<div align="center">
  
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [x] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [x] Pull request targets ``dev`` branch
- [x] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

Depends on #1072 (After merging 1072, path for websocket server has to be adjusted to `/websockets`)
Closes #904

### CODE REVIEW

**Review by SeDemal — APPROVED** [review]

**Review by manuel-rw — APPROVED** [review]

**Comment by jangrewe** [comment]
@Meierschlumpf Why is it necessary to set `$HOSTNAME`? In a docker container, that should *ALWAYS* be `0.0.0.0`.
In fact, this breaks Nginx for me, because it exists with:
```
2025/03/26 16:17:03 [emerg] 19#19: no host in upstream ":3001" in /etc/nginx/nginx.conf:11
```
As my `nginx.conf` looks like this:
```events {
    worker_connections 1024;
}

http {
    server {
        listen 7575;

        # Route websockets traffic to port 3001
        location /websockets {
            proxy_pass http://:3001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $http_host;
        }

        # Route all other traffic to port 3000
        location / {
            proxy_pass http://:3000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        }
    }
}
```
I'm not sure where the value for `$HOSTNAME` is supposed to come from, but anything other than `0.0.0.0` makes no sense...
How about at least providing a sane default (`0.0.0.0`) unless overridden, by putting this at the top of `run.sh`?
```
#!/bin/bash

: ${HOSTNAME:=0.0.0.0}

```
Alternatively, you could add this to the Dockerfile:
```
ENV HOSTNAME=0.0.0.0
```

**Comment by jangrewe** [comment]
When setting `HOSTNAME=127.0.0.1` to make Nginx start, i now get redirected to `http://localhost:3000/init` - which is of course not accessible.
I would suggest using `$HOSTNAME` to be used for the actual, external hostname under which the container is accessible, and setting the `proxy_pass` always to `127.0.0.1`, becauese Nginx and the other services are obviously running on the same host.

**Comment by jangrewe** [comment]
And another observation: As i'm using Nginx (with HTTPS) as a system-wide reverse proxy for all my containers, this seems to royally break something because the protocol is not ignored (i suppose):
```
Mar 26 17:36:16 hades nerdctl[3590661]: Failed to proxy https://localhost:3000/en/init [Error: write EPROTO 58525864697F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
Mar 26 17:36:16 hades nerdctl[3590661]: ] {
Mar 26 17:36:16 hades nerdctl[3590661]:   errno: -71,
Mar 26 17:36:16 hades nerdctl[3590661]:   code: 'EPROTO',
Mar 26 17:36:16 hades nerdctl[3590661]:   syscall: 'write'
Mar 26 17:36:16 hades nerdctl[3590661]: }
Mar 26 17:36:16 hades nerdctl[3590661]: [Error: write EPROTO 58525864697F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
Mar 26 17:36:16 hades nerdctl[3590661]: ] {
Mar 26 17:36:16 hades nerdctl[3590661]:   errno: -71,
Mar 26 17:36:16 hades nerdctl[3590661]:   code: 'EPROTO',
Mar 26 17:36:16 hades nerdctl[3590661]:   syscall: 'write'
Mar 26 17:36:16 hades nerdctl[3590661]: }
Mar 26 17:36:43 hades nerdctl[3590661]: 2025-03-26T16:36:43.092Z info: tRPC request from server-fetch by user 'undefined (undefined)'
Mar 26 17:36:43 hades nerdctl[3590661]: 2025-03-26T16:36:43.107Z info: tRPC request from server-fetch by user 'undefined (undefined)'
```

**Comment by Meierschlumpf** [comment]
Hey @jangrewe thank you for the insights. Can you please open an issue. Because posting this here in this pr will get lost as we will not look at old prs

**Pull request merged**
