### PR TITLE
feat: add column count and is public options to board creation modal

### PR DESCRIPTION
**Pull request by Meierschlumpf**
<br/>
<div align="center">
  
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [x] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [x] Pull request targets ``dev`` branch
- [x] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

image

### CODE REVIEW

**Comment by Meierschlumpf** [comment]
Will fix tests tomorrow

**Review by SeDemal — COMMENTED** [review]
Should we really force a maximum?
We've had the comment that x amount of columns wasn't enough and I'm sure we'll get more.
I really do like the use of the slider more than an unlimited NumberInput.
I suggest limiting to 100 so people can think of it as percents. (That would be a big slider though)
What do you think?
(Also there's an unrelated error, not sure what's that about)

**Comment by Meierschlumpf** [comment]
I would leave it for now at 24. When somebody really want's more we can add this feature later. I mean it's not really hard to do so

**Comment by manuel-rw** [comment]
I think 24 is a good default to start with. We can still adjust this value later. Our early adopters will provide feedback and say whether they like this size

**Review by manuel-rw — APPROVED** [review]

**Pull request merged**
